apiVersion: apps/v1
kind: Deployment
metadata:
  name: timer-app
  labels:
    app: timer-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: timer-app
  template:
    metadata:
      labels:
        app: timer-app
    spec:
      containers:
      - name: timer-app
        image: yaronpr/printer:latest
        env:        
        - name: PROCESS_SECOND
          value: "45"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - timer-app
            topologyKey: "kubernetes.io/hostname"